### ISSUE TITLE
Add the ability to configure admin extensions

### ISSUE THREAD

**Issue by gremo** [kunicmarko20/SonataAutoConfigureBundle#15]
Admin extension can be easly configured:

```yml
App\Admin\Extension\:
    resource: '../../src/Admin/Extension'
    tags: [{ name: 'sonata.admin.extension' }]
```

... but, if you need a global extension, you need to waste another two lines of code:

```yml
App\Admin\Extension\GlobalExtension:
    tags: [{ name: 'sonata.admin.extension', global: true }]
```

It would be nice a new annotation to configure admin extensions.
