### ISSUE TITLE
Autoconfiguration of Extensions

### ISSUE THREAD

**Issue by kunicmarko20** [kunicmarko20/SonataAutoConfigureBundle#21]
I am looking at this and I think this is wrong, the point of the bundle is to autoconfigure stuff not to require someone to add annotation, I am thinking of adding logic of guessing the target admin, if not found we set global true and if there is an annotation, we ignore our guessing logic. wdyt @gremo ?

**Comment by gremo** [comment]
I disagree. I think that this is out of the scope of the bundle (guessing, making it global if no targets, etc.). IMHO we just need to "replicate" the behavior of the tag, with `global` and `target` attributes. 

The `target` attribute of the tag seems wrong to me (but this is a SonataAdmin fault, of course) because most of the time, you'll use the configuration:

```yml
sonata_admin:
    extensions:
        app.publish.extension:
            admins:
                - app.admin.article
            implements:
                - App\Publish\PublishStatusInterface
            excludes:
                - app.admin.blog
                - app.admin.news
            extends:
                - App\Document\Blog
            instanceof:
                -  App\Document\Page
            uses:
                -  App\Trait\Timestampable
```

Mixing both `target` attribute and configuration will lead to a mess.

It is fine, as you say, to "guess" for entity and controller of an admin, but for extensions it seems wrong to me.

**Comment by kunicmarko20** [comment]
I don't see a value in admin extension class that requires you to have annotation, then you can just register it as a service, it is not autoconfigured either way.

**Comment by gremo** [comment]
> I don't see a value in admin extension class that requires you to have annotation, then you can just register it as a service, it is not autoconfigured either way.

The annotation is only needed to make it global (and maybe configure the target), without repeating the service, as explained here https://github.com/kunicmarko20/SonataAutoConfigureBundle/issues/15

**Comment by kunicmarko20** [comment]
Hm, ok, I can see the value in that, btw:

```yaml
App\Admin\Extension\:
    resource: '../../src/Admin/Extension'
    tags: [{ name: 'sonata.admin.extension' }]
```

This is not needed anymore.

**Comment by kunicmarko20** [comment]
https://github.com/kunicmarko20/SonataAutoConfigureBundle/releases/tag/0.6.0

**Comment by gremo** [comment]
> This is not needed anymore.

Really? Why is not needed? The compiler pass do its stuff for services tagged with `sonata.admin.extension`: who is adding this tag? I think this code:

```yml
App\Admin\Extension\:
    resource: '../../src/Admin/Extension'
    tags: [{ name: 'sonata.admin.extension' }]
```
