### ISSUE TITLE
Setting defaults using the configuration

### ISSUE THREAD

**Issue by gremo** [kunicmarko20/SonataAutoConfigureBundle#7]
How about setting defaults using the configuration? Sometimes I need annotations just to change the `labelTranslatorStrategy `or the `labelCatalogue`.

```yml
sonata_auto_configure:
    defaults:
        label_catalogue: admin
        label_translator_strategy: sonata.admin.label.strategy.underscore
        show_mosaic_button: false
```
